# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56472c0fe22e680e10c49999648cfac06be0fbd757abe2dbef27bcf97710d5f106af7d1787247ad2dad99cfc2dfba311bcb89a827e175d99d6164551e896caad

test:
  secret_key_base: 606ce8aeb064e14c375435e9993ca135320f8ca6be15c4d8c5f6a46dcc5615a7d8714c0309ee70db3193730aedb5806e651eec517a8b26dee74be3bbe61a5d85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
